### PR TITLE
LastWill- & SpeedRegulator functionality 

### PR DESCRIPTION
**Pull request by AlbinKarlsson**
In this merge the following has been added:
- A seekbar where the user can adjust speed. Speed can be adjusted for both "forward" and "backward". 

- A lastWill method has been implemented. The functionality of this method will make sure that:
When the connection is lost, the car will automatically come to a stop smoothly (by using a method that will slow down the speed gradually until a complete stop).

The code has been tested manually by two developers: Albin and Felix. 

The merge will fullfill the acceptance criteria for issue #34 and #25. 

 

### :ballot_box_with_check: Definition of Done checklist
- [x] Meaningful title and valuable description in pull request
- [x] Code change tested manually if not covered by automated tests
- [x] Pull request linked to one or more issues/stories
- [x] Acceptance criteria of the linked stories satisfied
- [x] Code change comprehended by those who approved it
- [x] State of target branch maintained or improved after the code change

### CODE REVIEW

**Review by Lindet94 — CHANGES_REQUESTED** [review]
Changes:

- Method onStartTrackingTouch will be implemented in a later issue?
- Private static boolean check? - Ambiguous variable, can be changed?
- Should also test code further with automated tests.
- If speed >10 in lastWill. Add comment for purpose of this for better understanding.

**Comment by Valkama1** [comment]
> Changes:
> 
>     * Method onStartTrackingTouch will be implemented in a later issue?
> 
>     * Private static boolean check? - Ambiguous variable, can be changed?
> 
>     * Should also test code further with automated tests.
> 
>     * If speed >10 in lastWill. Add comment for purpose of this for better understanding.

- The method was auto generated no clue what to do with it for now
- Updated the check variable
- Yes we should, write some tests for next sprint
- Added some comments to explain the lastWill method

**Review by Lindet94 — DISMISSED** [review]
Looks good.

**Review by Lindet94 — COMMENTED** [review]
Ok.

**Review by Lindet94 — APPROVED** [review]
ok.

**Comment by AlbinKarlsson** [comment]
Test

**Review by Lindet94 — APPROVED** [review]

**Pull request merged**
