### PR TITLE
Add basic android project

### LINKED ISSUE #6: Create skeleton for app

### PR DESCRIPTION
**Pull request by Lindet94**

### CODE REVIEW

**Review by platisd — CHANGES_REQUESTED** [review]
Why is this not built on CI? :)

**Comment by Lindet94** [comment]
> Why is this not built on CI? :)

I was thinking that it can be connected with CI through Github, thats why I have another pull request about that. Perhaps this is not the way to do it, rather it should be built on CI in Android Studio? This is what I was trying to ask about yesterday before the lecture :)

**Comment by platisd** [comment]
I am not sure I follow. If you have a workflow that builds an android app, then commit it in the same branch and they will be "connected"

**Comment by Lindet94** [comment]
WIll commit changes through AndroidCI branch instead.

**Pull request closed without merging**
