### PR TITLE
Change name and file structure of project

### LINKED ISSUE #35: Refactoring
**Acceptance criteria:**

- [x] Change project package structure to something more appropriate
- [x] Put new camera feed code into project.
- [x] Fix support for API 32

### PR DESCRIPTION
**Pull request by Lindet94**
## Change name and file structure of project

Issue: Closes #35  
- Change project name
- Change project file structure

We decided to change the name of the project and the folder structure for it to be more personalized and aligned with our software.

### :ballot_box_with_check: Definition of Done checklist
- [x] Meaningful title and valuable description in pull request
- [x] Code change tested manually if not covered by automated tests
- [x] Pull request linked to one or more issues/stories
- [x] Acceptance criteria of the linked stories satisfied
- [x] Code change comprehended by those who approved it
- [x] State of target branch maintained or improved after the code change

### CODE REVIEW

**Comment by platisd** [comment]
> Change name and file structure of project

This should be the **title** of the pull request instead of the not-so-useful "Refactor". :+1:

**Review by AlbinKarlsson — APPROVED** [review]
Changing the name of the folder, not much code to review. It all looks good. It has also been tested multiple times that our project works.

**Review by AlbinKarlsson — DISMISSED** [review]

**Comment by Lindet94** [comment]
> > Change name and file structure of project
> 
> This should be the **title** of the pull request instead of the not-so-useful "Refactor". 👍

**Review by AlbinKarlsson — APPROVED** [review]
Good job. Thank you Platisd for you help.

**Pull request merged**
